version: "3"
services:
  influxdb:
    image: influxdb
    container_name: influxdb
    environment:
      - INFLUXDB_DB="telemetry"
    volumes:
      - db-data:/var/lib/influxdb
    restart: unless-stopped
  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - "influxdb"
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped
  server: 
    build: .
    container_name: server
    environment:
      - IN_DOCKER=true
    depends_on:
      - "influxdb"
    ports:
      - "8888:8888"
      - "6001:6001"
    restart: unless-stopped
  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - "server"
      - "grafana"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
volumes:
  db-data:
  grafana-storage: