version: "3.5"
services:
  nginx:
    volumes:
      - ./nginx/conf.d/dev:/etc/nginx/conf.d
      - letsencrypt-config:/etc/letsencrypt #hack to override prod /etc/letsencrypt
      - letsencrypt-www:/var/www/certbot # ditto
volumes:
  letsencrypt-config:
  letsencrypt-www:
