version: "3"
services:
  influxdb:
    image: influxdb
    container_name: influxdb
    environment:
      - INFLUXDB_DB="telemetry"
    volumes:
      - db-data:/var/lib/influxdb
    restart: unless-stopped
  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - "influxdb"
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped
  server: 
    image: "golang:1.11.2"
    container_name: server
    environment:
      - IN_DOCKER=true
    depends_on:
      - "influxdb"
    working_dir: /go/src/telemetry-server
    volumes: 
      - ./:/go/src/telemetry-server
    command: bash -c "go get -v -t ./... && go run main.go"
    ports:
      - "8888:8888"
      - "6001:6001"
    restart: unless-stopped
  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - "server"
      - "grafana"
      - "jenkins"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
  jenkins:
    build: ./jenkins
    container_name: jenkins
    volumes:
      - jenkins-home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/opt/telemetry-server
    ports:
      - "8080:8080"
volumes:
  db-data:
  grafana-storage:
  jenkins-home:
